### ISSUE TITLE
Is the project hosted anywhere? I would love to check it out

### ISSUE THREAD

**Issue by MitjaCH** [JeremyHefti/praisecamp#14]
Hi there,

I came across this repository and I'm interested in checking it out. However, I don't currently have the necessary API keys or URL to test it locally.

I was wondering if this project is already hosted somewhere online that I can access and explore? That would be really helpful for me to get a better understanding of the project.

Thanks in advance for your help!

**Comment by nxkzty** [comment]
Hello @MitjaCH 
Thank you for your interest but we are not currently hosting this project anywhere, but we will try to do so asap.

**Comment by MitjaCH** [comment]
fwaeh
